# fly.toml file generated for penn-clubs-django-wsgi on 2023-02-06T23:58:14-05:00

app = "penn-clubs-django-wsgi"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  REDIS_HOST = "137.66.44.44"
  AWS_STORAGE_BUCKET_NAME = "penn.clubs"

[build]
  dockerfile = "Dockerfile"
  

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
